
-
    prefix: ~
    routes:
        -
            name: index
            controller: Index
            action: Show
            match: /

        -
            name: sigunup
            controller: User
            action: Signup
            match: /signup

        - 
            name: user_topic
            controller: Topic
            action: Show
            match: /(\w+)/(\d+)
            keys: [uid, tid]

-
    prefix: /user
    routes:
        -
            name: user_show
            controller: User
            action: Show
            match: /(\d+)
            keys: [id]
        
        -
            name: user_list
            controller: User
            action: List
            match: /list

