
-
    name: index
    controller: Index
    action: Show
    prefix: /

-
    name: user_show
    controller: User
    action: Show
    prefix: /user
    match: /(\d+)
    keys: [id]
    

-
    name: signup
    controller: User
    action: Signup
    match: /signup

-
    name: user_topic
    controller: Topic
    action: Show
    match: /(\w+)/(\d+)
    keys: [uid, tid]

-
    name: user_show
    controller: User
    action: Show
    prefix: /user
    match: /aaa/(\d+)
    keys: [id]
