name: Topics
env: dev

http:
    host: roydong.com
    port: 80
    timeout: 30

log_dir: log/
static_dir: ~

error_handler:
    not_found: {controller: Error, action: NotFound}
    server_error: {controller: Error, action: ServerError}


sql:
    host: 192.168.10.192
    port: 3306
    user: root
    pass: d
    dbname: topic

