


http:
    host: roydong.com
    port: 80
    timeout: 30

name: Roy Dong
env: dev

log_dir: ~
static_dir: ~

error_handler:
    not_found: {controller: Error, action: NotFound}
    server_error: {controller: Error, action: ServerError}

