


http:
    host: roydong.com
    port: 8080
    timeout: 30

name: Roy Dong
env: dev

log_dir: ~
static_dir: ~

error_handler:
    not_found: {controller: Error, action: NotFound1}
    server_error: {controller: Error, action: ServerError1}

