name: Topics
env: dev

http:
    host: notes.roydong.com
    port: 80

log_dir: log/
static_dir: ~

error_handler:
    not_found: {controller: Error, action: NotFound}
    server_error: {controller: Error, action: ServerError}


sql:
    host: localhost
    port: 3306
    user: root
    pass: d
    dbname: topic

