-
    prefix: ~
    routes:
        -
            name: sigunup
            controller: User
            action: Signup
            pattern: /signup

        -
            name: signin
            controller: User
            action: Signin
            pattern: /signin

        - 
            name: setting
            controller: User 
            action: Setting
            pattern: /setting

-
    prefix: /user
    routes:
        -
            name: user_show
            controller: User
            action: Show
            pattern: /(\d+)
            keys: [id]
        
        -
            name: user_list
            controller: User
            action: List
            pattern: /list

-
    prefix: /topic
    routes:
        -
            name: topic_new
            controller: Topic
            action: New
            pattern: /new
        
