
-
    prefix: ~
    routes:
        -
            name: index
            controller: Index
            action: Show
            pattern: /

        -
            name: sigunup
            controller: User
            action: Signup
            pattern: /signup

        - 
            name: user_topic
            controller: User 
            action: Topic 
            pattern: /(\d+)/(\d+)
            keys: [uid, tid]

        - 
            name: home
            controller: Index
            action: Home 
            pattern: /home

-
    prefix: /user
    routes:
        -
            name: user_show
            controller: User
            action: Show
            pattern: /(\d+)
            keys: [id]
        
        -
            name: user_list
            controller: User
            action: List
            pattern: /list

        
