-
    prefix: /topic
    routes:
        -
            name: topic_show
            controller: topic
            action: Show 
            pattern: /(\d+)
            keys: [id]

-
    prefix: /admin
    routes:
        -
            name: sigunup
            controller: admin_user
            action: Signup
            pattern: /signup

        -
            name: signin
            controller: admin_user
            action: Signin
            pattern: /signin

        - 
            name: setting
            controller: admin_user
            action: Setting
            pattern: /setting


-
    prefix: /admin/topic
    routes:
        -
            name: admin_topic_new
            controller: admin_topic
            action: New
            pattern: /new
        
        -
            name: admin_topics
            controller: admin_topic
            action: Show 
            pattern: /
        
        -
            name: admin_topic_edit
            controller: admin_topic
            action: Show 
            pattern: /(\d+)
            keys: [id]
